<?php

namespace App\Services\ELearning;

class ReceptionFormConfig
{
    public static function getConfig(): array
    {
        return [
            'registration-form' => [
                'fields' => [
                    ['name' => 'guest_name', 'label' => 'Nama Tamu', 'type' => 'text', 'required' => true],
                    ['name' => 'booking_reference', 'label' => 'Booking Reference', 'type' => 'text', 'required' => true],
                    ['name' => 'email', 'label' => 'Email', 'type' => 'email', 'required' => false],
                    ['name' => 'phone', 'label' => 'No. Telepon', 'type' => 'text', 'required' => true],
                    ['name' => 'id_type', 'label' => 'Tipe Identitas', 'type' => 'select', 'options' => ['KTP', 'Passport', 'SIM', 'KITAS'], 'required' => true],
                    ['name' => 'id_number', 'label' => 'No. Identitas', 'type' => 'text', 'required' => true],
                    ['name' => 'nationality', 'label' => 'Kewarganegaraan', 'type' => 'text', 'required' => true],
                    ['name' => 'date_of_birth', 'label' => 'Tanggal Lahir', 'type' => 'date', 'required' => true],
                    ['name' => 'address', 'label' => 'Alamat', 'type' => 'textarea', 'required' => true],
                    ['name' => 'check_in', 'label' => 'Check-in', 'type' => 'date', 'required' => true],
                    ['name' => 'check_out', 'label' => 'Check-out', 'type' => 'date', 'required' => true],
                    ['name' => 'room_type', 'label' => 'Tipe Kamar', 'type' => 'select', 'options' => ['Standard', 'Superior', 'Deluxe', 'Executive', 'Suite'], 'required' => true],
                    ['name' => 'number_of_guests', 'label' => 'Jumlah Tamu', 'type' => 'number', 'required' => true],
                    ['name' => 'arrival_time', 'label' => 'Estimasi Waktu Check-in', 'type' => 'text', 'required' => true],
                    ['name' => 'payment_method', 'label' => 'Metode Pembayaran', 'type' => 'select', 'options' => ['Cash', 'Credit Card', 'Transfer', 'Company Account'], 'required' => true],
                ],
                'answers' => [
                    'guest_name' => 'Andika Pratama',
                    'booking_reference' => 'INV-20260628-0001',
                    'email' => 'andika.pratama@nusaindah.co.id',
                    'phone' => '081234567890',
                    'id_type' => 'KTP',
                    'id_number' => '7501051234567890',
                    'nationality' => 'Indonesia',
                    'date_of_birth' => '1985-03-15',
                    'address' => 'Jl. Sudirman No. 45, Jakarta Selatan',
                    'check_in' => '2026-06-29',
                    'check_out' => '2026-06-30',
                    'room_type' => 'Deluxe',
                    'number_of_guests' => '2',
                    'arrival_time' => '09.00',
                    'payment_method' => 'Transfer',
                ],
                'clues' => [
                    'guest_name' => 'Perhatikan nama tamu di awal percakapan.',
                    'booking_reference' => 'Booking reference tertera setelah kata "Booking Reference".',
                    'email' => 'Email terdapat pada detail reservasi.',
                    'phone' => 'Nomor telepon tertera setelah kata "No. Telepon".',
                    'id_type' => 'Jenis identitas yang disebutkan dalam percakapan.',
                    'id_number' => 'Nomor identitas terdapat pada data tamu.',
                    'nationality' => 'Kewarganegaraan tamu angegeben.',
                    'date_of_birth' => 'Tanggal lahir tertera setelah nama tamu.',
                    'address' => 'Alamat lengkap tertera dalam percakapan.',
                    'check_in' => 'Check-in adalah hari setelah reservasi, besok dari today.',
                    'check_out' => 'Durasi menginap adalah 2 malam dari tanggal check-in.',
                    'room_type' => 'Tipe kamar yang dipesan adalah Deluxe.',
                    'number_of_guests' => 'Jumlah tamu termasuk dalam reservasi.',
                    'arrival_time' => 'Estimasi waktu check-in tertera dalam percakapan.',
                    'payment_method' => 'Metode pembayaran disebutkan di akhir percakapan.',
                ],
            ],

            'guest-card' => [
                'fields' => [
                    ['name' => 'guest_name', 'label' => 'Nama Tamu', 'type' => 'text', 'required' => true],
                    ['name' => 'room_number', 'label' => 'No. Kamar', 'type' => 'text', 'required' => true],
                    ['name' => 'check_in', 'label' => 'Check-in', 'type' => 'date', 'required' => true],
                    ['name' => 'check_in_time', 'label' => 'Waktu Check-in', 'type' => 'text', 'required' => true],
                    ['name' => 'check_out', 'label' => 'Check-out', 'type' => 'date', 'required' => true],
                    ['name' => 'room_type', 'label' => 'Tipe Kamar', 'type' => 'text', 'required' => true],
                    ['name' => 'room_rate', 'label' => 'Room Rate', 'type' => 'text', 'required' => true],
                    ['name' => 'address', 'label' => 'Alamat', 'type' => 'textarea', 'required' => true],
                    ['name' => 'phone', 'label' => 'No. HP', 'type' => 'text', 'required' => true],
                    ['name' => 'email', 'label' => 'Email', 'type' => 'email', 'required' => false],
                    ['name' => 'gender', 'label' => 'Jenis Kelamin', 'type' => 'select', 'options' => ['Laki-laki', 'Perempuan'], 'required' => true],
                    ['name' => 'nationality', 'label' => 'Kewarganegaraan', 'type' => 'text', 'required' => true],
                    ['name' => 'id_number', 'label' => 'No. Identitas', 'type' => 'text', 'required' => true],
                    ['name' => 'wake_up_call', 'label' => 'Wake-up Call', 'type' => 'text', 'required' => false],
                    ['name' => 'breakfast_location', 'label' => 'Breakfast', 'type' => 'text', 'required' => false],
                ],
                'answers' => [
                    'guest_name' => 'Budi Santoso',
                    'room_number' => '205',
                    'check_in' => '2026-06-28',
                    'check_in_time' => '14.30',
                    'check_out' => '2026-06-30',
                    'room_type' => 'Superior',
                    'room_rate' => '650000',
                    'address' => 'Jl. Ahmad Yani No. 12, Semarang',
                    'phone' => '082345678901',
                    'email' => 'budi.santoso@gmail.com',
                    'gender' => 'Laki-laki',
                    'nationality' => 'Indonesia',
                    'id_number' => '3310054567891234',
                    'wake_up_call' => '06.30',
                    'breakfast_location' => 'Kamar',
                ],
                'clues' => [
                    'guest_name' => 'Nama tamu tertera di awal deskripsi.',
                    'room_number' => 'Nomor kamar disebutkan dalam deskripsi.',
                    'check_in' => 'Tanggal check-in hari ini.',
                    'check_in_time' => 'Waktu check-in tertera dalam deskripsi.',
                    'check_out' => 'Check-out 2 malam setelah check-in.',
                    'room_type' => 'Tipe kamar disebutkan dalam deskripsi.',
                    'room_rate' => 'Room rate tertera dalam deskripsi.',
                    'address' => 'Alamat tamu tertera dalam data.',
                    'phone' => 'Nomor HP tertera dalam data tamu.',
                    'email' => 'Email tertera dalam deskripsi.',
                    'gender' => 'Jenis kelamin tamu tertera dalam deskripsi.',
                    'nationality' => 'Kewarganegaraan tertera dalam deskripsi.',
                    'id_number' => 'Nomor identitas dengan jenis KTP.',
                    'wake_up_call' => 'Wake-up call yang diminta tamu.',
                    'breakfast_location' => 'Lokasi breakfast yang diminta.',
                ],
            ],

            'breakfast-coupon' => [
                'fields' => [
                    ['name' => 'guest_name', 'label' => 'Nama Tamu', 'type' => 'text', 'required' => true],
                    ['name' => 'room_number', 'label' => 'No. Kamar', 'type' => 'text', 'required' => true],
                    ['name' => 'check_in', 'label' => 'Check-in', 'type' => 'date', 'required' => true],
                    ['name' => 'check_out', 'label' => 'Check-out', 'type' => 'date', 'required' => true],
                    ['name' => 'number_of_coupons', 'label' => 'Jumlah Tamu', 'type' => 'number', 'required' => true],
                    ['name' => 'coupon_date_1', 'label' => 'Tanggal Coupon 1', 'type' => 'date', 'required' => true],
                    ['name' => 'coupon_count_1', 'label' => 'Jumlah Coupon Tanggal 1', 'type' => 'number', 'required' => true],
                    ['name' => 'coupon_date_2', 'label' => 'Tanggal Coupon 2', 'type' => 'date', 'required' => true],
                    ['name' => 'coupon_count_2', 'label' => 'Jumlah Coupon Tanggal 2', 'type' => 'number', 'required' => true],
                    ['name' => 'total_coupons', 'label' => 'Total Coupon', 'type' => 'number', 'required' => true],
                    ['name' => 'breakfast_time', 'label' => 'Waktu Breakfast', 'type' => 'text', 'required' => true],
                    ['name' => 'room_type', 'label' => 'Tipe Kamar', 'type' => 'text', 'required' => true],
                ],
                'answers' => [
                    'guest_name' => 'Sari Dewi',
                    'room_number' => '305',
                    'check_in' => '2026-06-27',
                    'check_out' => '2026-06-29',
                    'number_of_coupons' => '2',
                    'coupon_date_1' => '2026-06-28',
                    'coupon_count_1' => '2',
                    'coupon_date_2' => '2026-06-29',
                    'coupon_count_2' => '2',
                    'total_coupons' => '4',
                    'breakfast_time' => '07.00-10.00',
                    'room_type' => 'Superior',
                ],
                'clues' => [
                    'guest_name' => 'Nama tamu yang check-in.',
                    'room_number' => 'Nomor kamar tertera.',
                    'check_in' => 'Tanggal check-in asli.',
                    'check_out' => 'Tanggal check-out asli.',
                    'number_of_coupons' => 'Jumlah tamu untuk breakfast.',
                    'coupon_date_1' => 'Tanggal breakfast pertama.',
                    'coupon_count_1' => 'Coupon untuk tanggal pertama.',
                    'coupon_date_2' => 'Tanggal breakfast kedua.',
                    'coupon_count_2' => 'Coupon untuk tanggal kedua.',
                    'total_coupons' => 'Total semua coupon.',
                    'breakfast_time' => 'Waktu makan breakfast di restoran.',
                    'room_type' => 'Tipe kamar yang dipesan.',
                ],
            ],

            'guest-in-house' => [
                'fields' => [
                    ['name' => 'report_date', 'label' => 'Tanggal Laporan', 'type' => 'date', 'required' => true],
                    ['name' => 'report_time', 'label' => 'Waktu Laporan', 'type' => 'text', 'required' => true],
                    ['name' => 'room_201_guest', 'label' => 'Kamar 201 - Tamu', 'type' => 'text', 'required' => true],
                    ['name' => 'room_201_checkin', 'label' => 'Kamar 201 - Check-in', 'type' => 'date', 'required' => true],
                    ['name' => 'room_201_checkout', 'label' => 'Kamar 201 - Check-out', 'type' => 'date', 'required' => true],
                    ['name' => 'room_201_rate', 'label' => 'Kamar 201 - Rate', 'type' => 'text', 'required' => true],
                    ['name' => 'room_201_payment', 'label' => 'Kamar 201 - Pembayaran', 'type' => 'text', 'required' => true],
                    ['name' => 'room_202_guest', 'label' => 'Kamar 202 - Tamu', 'type' => 'text', 'required' => true],
                    ['name' => 'room_202_checkin', 'label' => 'Kamar 202 - Check-in', 'type' => 'date', 'required' => true],
                    ['name' => 'room_202_checkout', 'label' => 'Kamar 202 - Check-out', 'type' => 'date', 'required' => true],
                    ['name' => 'room_202_rate', 'label' => 'Kamar 202 - Rate', 'type' => 'text', 'required' => true],
                    ['name' => 'room_202_payment', 'label' => 'Kamar 202 - Pembayaran', 'type' => 'text', 'required' => true],
                    ['name' => 'total_rooms', 'label' => 'Total Kamar', 'type' => 'number', 'required' => true],
                    ['name' => 'total_guests', 'label' => 'Total Tamu', 'type' => 'number', 'required' => true],
                    ['name' => 'total_revenue', 'label' => 'Total Revenue', 'type' => 'text', 'required' => true],
                ],
                'answers' => [
                    'report_date' => '2026-06-28',
                    'report_time' => '18.00',
                    'room_201_guest' => 'Ratna Kusuma',
                    'room_201_checkin' => '2026-06-27',
                    'room_201_checkout' => '2026-06-29',
                    'room_201_rate' => '750000',
                    'room_201_payment' => 'Cash',
                    'room_202_guest' => 'Doni Firmansyah',
                    'room_202_checkin' => '2026-06-28',
                    'room_202_checkout' => '2026-07-01',
                    'room_202_rate' => '650000',
                    'room_202_payment' => 'Credit Card',
                    'total_rooms' => '4',
                    'total_guests' => '6',
                    'total_revenue' => '2900000',
                ],
                'clues' => [
                    'report_date' => 'Tanggal laporan adalah hari ini.',
                    'report_time' => 'Waktu laporan tertera.',
                    'room_201_guest' => 'Nama tamu kamar 201.',
                    'room_201_checkin' => 'Tanggal check-in kamar 201.',
                    'room_201_checkout' => 'Tanggal check-out kamar 201.',
                    'room_201_rate' => 'Rate kamar 201 per malam.',
                    'room_201_payment' => 'Metode pembayaran tamu 201.',
                    'room_202_guest' => 'Nama tamu kamar 202.',
                    'room_202_checkin' => 'Tanggal check-in kamar 202.',
                    'room_202_checkout' => 'Tanggal check-out kamar 202.',
                    'room_202_rate' => 'Rate kamar 202 per malam.',
                    'room_202_payment' => 'Metode pembayaran tamu 202.',
                    'total_rooms' => 'Hitung total kamar yang terisi.',
                    'total_guests' => 'Hitung total semua tamu.',
                    'total_revenue' => 'Total semua revenue kamar.',
                ],
            ],

            'arrival-book' => [
                'fields' => [
                    ['name' => 'arrival_date', 'label' => 'Tanggal Arrival', 'type' => 'date', 'required' => true],
                    ['name' => 'room_201_guest', 'label' => 'Kamar 201 - Tamu', 'type' => 'text', 'required' => true],
                    ['name' => 'room_201_origin', 'label' => 'Kamar 201 - Origin', 'type' => 'text', 'required' => true],
                    ['name' => 'room_201_flight', 'label' => 'Kamar 201 - Flight', 'type' => 'text', 'required' => true],
                    ['name' => 'room_201_arrival_time', 'label' => 'Kamar 201 - Arrival Time', 'type' => 'text', 'required' => true],
                    ['name' => 'room_201_transport', 'label' => 'Kamar 201 - Transport', 'type' => 'text', 'required' => true],
                    ['name' => 'room_201_purpose', 'label' => 'Kamar 201 - Purpose', 'type' => 'text', 'required' => true],
                    ['name' => 'room_201_los', 'label' => 'Kamar 201 - LOS', 'type' => 'number', 'required' => true],
                    ['name' => 'room_201_rate', 'label' => 'Kamar 201 - Rate', 'type' => 'text', 'required' => true],
                    ['name' => 'room_203_guest', 'label' => 'Kamar 203 - Tamu', 'type' => 'text', 'required' => true],
                    ['name' => 'room_203_origin', 'label' => 'Kamar 203 - Origin', 'type' => 'text', 'required' => true],
                    ['name' => 'room_203_flight', 'label' => 'Kamar 203 - Flight', 'type' => 'text', 'required' => true],
                    ['name' => 'room_203_arrival_time', 'label' => 'Kamar 203 - Arrival Time', 'type' => 'text', 'required' => true],
                    ['name' => 'room_203_transport', 'label' => 'Kamar 203 - Transport', 'type' => 'text', 'required' => true],
                    ['name' => 'room_203_purpose', 'label' => 'Kamar 203 - Purpose', 'type' => 'text', 'required' => true],
                    ['name' => 'total_arrival', 'label' => 'Total Arrival', 'type' => 'number', 'required' => true],
                    ['name' => 'expected_revenue', 'label' => 'Expected Revenue', 'type' => 'text', 'required' => true],
                ],
                'answers' => [
                    'arrival_date' => '2026-06-29',
                    'room_201_guest' => 'Ratna Kusuma',
                    'room_201_origin' => 'Jakarta',
                    'room_201_flight' => 'GA 601',
                    'room_201_arrival_time' => '10.30',
                    'room_201_transport' => 'Self',
                    'room_201_purpose' => 'Business',
                    'room_201_los' => '2',
                    'room_201_rate' => '750000',
                    'room_203_guest' => 'Hendra Wijaya',
                    'room_203_origin' => 'Surabaya',
                    'room_203_flight' => 'SI 205',
                    'room_203_arrival_time' => '14.00',
                    'room_203_transport' => 'Hotel Transfer',
                    'room_203_purpose' => 'Leisure',
                    'total_arrival' => '3',
                    'expected_revenue' => '2150000',
                ],
                'clues' => [
                    'arrival_date' => 'Tanggal arrival yang diprediksi.',
                    'room_201_guest' => 'Nama tamu kamar 201.',
                    'room_201_origin' => 'Kota asal tamu 201.',
                    'room_201_flight' => 'Nomor penerbangan tamu 201.',
                    'room_201_arrival_time' => 'Waktu kedatangan tamu 201.',
                    'room_201_transport' => 'Jenis transportasi tamu 201.',
                    'room_201_purpose' => 'Tujuan kunjungan tamu 201.',
                    'room_201_los' => 'Lama menginap tamu 201.',
                    'room_201_rate' => 'Rate kamar 201.',
                    'room_203_guest' => 'Nama tamu kamar 203.',
                    'room_203_origin' => 'Kota asal tamu 203.',
                    'room_203_flight' => 'Nomor penerbangan tamu 203.',
                    'room_203_arrival_time' => 'Waktu kedatangan tamu 203.',
                    'room_203_transport' => 'Jenis transportasi tamu 203.',
                    'room_203_purpose' => 'Tujuan kunjungan tamu 203.',
                    'total_arrival' => 'Total tamu yang expected arrival.',
                    'expected_revenue' => 'Total expected revenue dari semua kamar.',
                ],
            ],
        ];
    }
}
