<?php

namespace App\Services\ELearning;

class ReceptionFormConfig2
{
    public static function getConfig(): array
    {
        return [
            'cash-receipt' => [
                'fields' => [
                    ['name' => 'receipt_number', 'label' => 'No. Receipt', 'type' => 'text', 'required' => true],
                    ['name' => 'guest_name', 'label' => 'Nama Tamu', 'type' => 'text', 'required' => true],
                    ['name' => 'room_number', 'label' => 'No. Kamar', 'type' => 'text', 'required' => true],
                    ['name' => 'room_charge', 'label' => 'Room Charge', 'type' => 'text', 'required' => true],
                    ['name' => 'tax', 'label' => 'Pajak (10%)', 'type' => 'text', 'required' => true],
                    ['name' => 'extra_charge', 'label' => 'Extra Charge', 'type' => 'text', 'required' => false],
                    ['name' => 'total', 'label' => 'Total', 'type' => 'text', 'required' => true],
                    ['name' => 'payment_method', 'label' => 'Metode Pembayaran', 'type' => 'select', 'options' => ['Cash', 'Credit Card', 'Transfer'], 'required' => true],
                    ['name' => 'amount_received', 'label' => 'Jumlah Diterima', 'type' => 'text', 'required' => false],
                    ['name' => 'change', 'label' => 'Kembalian', 'type' => 'text', 'required' => false],
                ],
                'answers' => [
                    'receipt_number' => 'CR-001',
                    'guest_name' => 'Ahmad Rizki',
                    'room_number' => '205',
                    'room_charge' => '650000',
                    'tax' => '65000',
                    'extra_charge' => '0',
                    'total' => '715000',
                    'payment_method' => 'Cash',
                    'amount_received' => '750000',
                    'change' => '35000',
                ],
                'clues' => [
                    'receipt_number' => 'Nomor receipt untuk pembayaran ini.',
                    'guest_name' => 'Nama tamu kamar 205.',
                    'room_number' => 'Nomor kamar yang dibayar.',
                    'room_charge' => 'Biaya kamar untuk 1 malam.',
                    'tax' => 'Pajak 10% dari room charge.',
                    'extra_charge' => 'Biaya tambahan jika ada.',
                    'total' => 'Total yang harus dibayar.',
                    'payment_method' => 'Metode pembayaran yang digunakan.',
                    'amount_received' => 'Jumlah uang yang diterima.',
                    'change' => 'Kembalian yang harus dikembalikan.',
                ],
            ],

            'departure-book' => [
                'fields' => [
                    ['name' => 'departure_date', 'label' => 'Tanggal Departure', 'type' => 'date', 'required' => true],
                    ['name' => 'room_201_guest', 'label' => 'Kamar 201 - Tamu', 'type' => 'text', 'required' => true],
                    ['name' => 'room_201_checkout_time', 'label' => 'Kamar 201 - Checkout Time', 'type' => 'text', 'required' => true],
                    ['name' => 'room_201_flight', 'label' => 'Kamar 201 - Flight', 'type' => 'text', 'required' => true],
                    ['name' => 'room_201_transport', 'label' => 'Kamar 201 - Transport', 'type' => 'select', 'options' => ['Yes', 'No'], 'required' => true],
                    ['name' => 'room_201_total_bill', 'label' => 'Kamar 201 - Total Bill', 'type' => 'text', 'required' => true],
                    ['name' => 'room_201_room_status', 'label' => 'Kamar 201 - Room Status', 'type' => 'text', 'required' => true],
                    ['name' => 'room_207_guest', 'label' => 'Kamar 207 - Tamu', 'type' => 'text', 'required' => true],
                    ['name' => 'room_207_checkout_time', 'label' => 'Kamar 207 - Checkout Time', 'type' => 'text', 'required' => true],
                    ['name' => 'room_207_flight', 'label' => 'Kamar 207 - Flight', 'type' => 'text', 'required' => true],
                    ['name' => 'room_207_transport', 'label' => 'Kamar 207 - Transport', 'type' => 'select', 'options' => ['Yes', 'No'], 'required' => true],
                    ['name' => 'room_207_total_bill', 'label' => 'Kamar 207 - Total Bill', 'type' => 'text', 'required' => true],
                    ['name' => 'total_departure', 'label' => 'Total Departure', 'type' => 'number', 'required' => true],
                    ['name' => 'total_revenue', 'label' => 'Total Revenue', 'type' => 'text', 'required' => true],
                ],
                'answers' => [
                    'departure_date' => '2026-06-29',
                    'room_201_guest' => 'Ratna Kusuma',
                    'room_201_checkout_time' => '12.00',
                    'room_201_flight' => 'GA 602',
                    'room_201_transport' => 'Yes',
                    'room_201_total_bill' => '1575000',
                    'room_201_room_status' => 'Dirty',
                    'room_207_guest' => 'Linda Tanoto',
                    'room_207_checkout_time' => '14.00',
                    'room_207_flight' => 'JT 891',
                    'room_207_transport' => 'No',
                    'room_207_total_bill' => '715000',
                    'total_departure' => '3',
                    'total_revenue' => '3472500',
                ],
                'clues' => [
                    'departure_date' => 'Tanggal departure yang diprediksi.',
                    'room_201_guest' => 'Nama tamu kamar 201.',
                    'room_201_checkout_time' => 'Waktu checkout standar.',
                    'room_201_flight' => 'Nomor penerbangan tamu 201.',
                    'room_201_transport' => 'Apakah butuh transportasi?',
                    'room_201_total_bill' => 'Total tagihan kamar 201.',
                    'room_201_room_status' => 'Status kamar setelah checkout.',
                    'room_207_guest' => 'Nama tamu kamar 207.',
                    'room_207_checkout_time' => 'Waktu checkout tamu 207.',
                    'room_207_flight' => 'Nomor penerbangan tamu 207.',
                    'room_207_transport' => 'Apakah tamu 207 butuh transportasi?',
                    'room_207_total_bill' => 'Total tagihan kamar 207.',
                    'total_departure' => 'Total kamar yang akan departure.',
                    'total_revenue' => 'Total revenue dari semua departure.',
                ],
            ],

            'expected-departure' => [
                'fields' => [
                    ['name' => 'departure_date', 'label' => 'Tanggal', 'type' => 'date', 'required' => true],
                    ['name' => 'room_202_guest', 'label' => 'Kamar 202 - Tamu', 'type' => 'text', 'required' => true],
                    ['name' => 'room_202_duration', 'label' => 'Kamar 202 - Durasi', 'type' => 'number', 'required' => true],
                    ['name' => 'room_202_total', 'label' => 'Kamar 202 - Total', 'type' => 'text', 'required' => true],
                    ['name' => 'room_202_payment', 'label' => 'Kamar 202 - Pembayaran', 'type' => 'text', 'required' => true],
                    ['name' => 'room_205_guest', 'label' => 'Kamar 205 - Tamu', 'type' => 'text', 'required' => true],
                    ['name' => 'room_205_duration', 'label' => 'Kamar 205 - Durasi', 'type' => 'number', 'required' => true],
                    ['name' => 'room_205_total', 'label' => 'Kamar 205 - Total', 'type' => 'text', 'required' => true],
                    ['name' => 'room_205_payment', 'label' => 'Kamar 205 - Pembayaran', 'type' => 'text', 'required' => true],
                    ['name' => 'room_305_guest', 'label' => 'Kamar 305 - Tamu', 'type' => 'text', 'required' => true],
                    ['name' => 'room_305_duration', 'label' => 'Kamar 305 - Durasi', 'type' => 'number', 'required' => true],
                    ['name' => 'room_305_total', 'label' => 'Kamar 305 - Total', 'type' => 'text', 'required' => true],
                    ['name' => 'room_305_payment', 'label' => 'Kamar 305 - Pembayaran', 'type' => 'text', 'required' => true],
                    ['name' => 'total_rooms', 'label' => 'Total Kamar', 'type' => 'number', 'required' => true],
                    ['name' => 'total_revenue', 'label' => 'Total Revenue', 'type' => 'text', 'required' => true],
                ],
                'answers' => [
                    'departure_date' => '2026-06-30',
                    'room_202_guest' => 'Doni Firmansyah',
                    'room_202_duration' => '3',
                    'room_202_total' => '2145000',
                    'room_202_payment' => 'Credit Card',
                    'room_205_guest' => 'Ahmad Rizki',
                    'room_205_duration' => '2',
                    'room_205_total' => '1430000',
                    'room_205_payment' => 'Cash',
                    'room_305_guest' => 'Sari Dewi',
                    'room_305_duration' => '3',
                    'room_305_total' => '2145000',
                    'room_305_payment' => 'Credit Card',
                    'total_rooms' => '3',
                    'total_revenue' => '5720000',
                ],
                'clues' => [
                    'departure_date' => 'Tanggal expected departure.',
                    'room_202_guest' => 'Nama tamu kamar 202.',
                    'room_202_duration' => 'Lama menginap dari 28 Juni.',
                    'room_202_total' => 'Total termasuk pajak 10%.',
                    'room_202_payment' => 'Metode pembayaran.',
                    'room_205_guest' => 'Nama tamu kamar 205.',
                    'room_205_duration' => 'Lama menginap dari 28 Juni.',
                    'room_205_total' => 'Total termasuk pajak 10%.',
                    'room_205_payment' => 'Metode pembayaran.',
                    'room_305_guest' => 'Nama tamu kamar 305.',
                    'room_305_duration' => 'Lama menginap dari 27 Juni.',
                    'room_305_total' => 'Total termasuk pajak 10%.',
                    'room_305_payment' => 'Metode pembayaran.',
                    'total_rooms' => 'Jumlah kamar yang expected departure.',
                    'total_revenue' => 'Total semua revenue.',
                ],
            ],

            'guest-bill' => [
                'fields' => [
                    ['name' => 'guest_name', 'label' => 'Nama Tamu', 'type' => 'text', 'required' => true],
                    ['name' => 'room_number', 'label' => 'No. Kamar', 'type' => 'text', 'required' => true],
                    ['name' => 'checkout_date', 'label' => 'Tanggal Checkout', 'type' => 'date', 'required' => true],
                    ['name' => 'room_charge_1', 'label' => 'Room Charge 27 Juni', 'type' => 'text', 'required' => true],
                    ['name' => 'room_charge_2', 'label' => 'Room Charge 28 Juni', 'type' => 'text', 'required' => true],
                    ['name' => 'room_tax', 'label' => 'Room Tax (10%)', 'type' => 'text', 'required' => true],
                    ['name' => 'extra_minibar', 'label' => 'Extra - Minibar', 'type' => 'text', 'required' => false],
                    ['name' => 'extra_restaurant', 'label' => 'Extra - Restaurant', 'type' => 'text', 'required' => false],
                    ['name' => 'extra_laundry', 'label' => 'Extra - Laundry', 'type' => 'text', 'required' => false],
                    ['name' => 'extra_transfer', 'label' => 'Extra - Transfer', 'type' => 'text', 'required' => false],
                    ['name' => 'extra_bed', 'label' => 'Extra - Extra Bed', 'type' => 'text', 'required' => false],
                    ['name' => 'extra_subtotal', 'label' => 'Extra Subtotal', 'type' => 'text', 'required' => true],
                    ['name' => 'extra_tax', 'label' => 'Extra Tax (10%)', 'type' => 'text', 'required' => true],
                    ['name' => 'grand_total', 'label' => 'Grand Total', 'type' => 'text', 'required' => true],
                    ['name' => 'paid_at_checkin', 'label' => 'Paid at Check-in', 'type' => 'text', 'required' => true],
                    ['name' => 'balance_due', 'label' => 'Balance Due', 'type' => 'text', 'required' => true],
                ],
                'answers' => [
                    'guest_name' => 'Ratna Kusuma',
                    'room_number' => '201',
                    'checkout_date' => '2026-06-29',
                    'room_charge_1' => '750000',
                    'room_charge_2' => '750000',
                    'room_tax' => '150000',
                    'extra_minibar' => '125000',
                    'extra_restaurant' => '285000',
                    'extra_laundry' => '75000',
                    'extra_transfer' => '150000',
                    'extra_bed' => '150000',
                    'extra_subtotal' => '785000',
                    'extra_tax' => '78500',
                    'grand_total' => '2513500',
                    'paid_at_checkin' => '1650000',
                    'balance_due' => '863500',
                ],
                'clues' => [
                    'guest_name' => 'Nama tamu yang checkout.',
                    'room_number' => 'Nomor kamar.',
                    'checkout_date' => 'Tanggal checkout hari ini.',
                    'room_charge_1' => 'Biaya kamar tanggal 27 Juni.',
                    'room_charge_2' => 'Biaya kamar tanggal 28 Juni.',
                    'room_tax' => 'Pajak 10% dari total room charge.',
                    'extra_minibar' => 'Biaya minibar tanggal 27 Juni.',
                    'extra_restaurant' => 'Biaya makan malam restoran.',
                    'extra_laundry' => 'Biaya laundry.',
                    'extra_transfer' => 'Biaya antar jemput bandara.',
                    'extra_bed' => 'Biaya extra bed.',
                    'extra_subtotal' => 'Total semua extra charges.',
                    'extra_tax' => 'Pajak 10% dari extra subtotal.',
                    'grand_total' => 'Grand total = room + room tax + extra + extra tax.',
                    'paid_at_checkin' => 'Jumlah yang sudah dibayar saat check-in.',
                    'balance_due' => 'Sisa yang harus dibayar = grand total - paid.',
                ],
            ],
        ];
    }
}
