<?php

namespace App\Services\ELearning;

class ReservationFormConfig2
{
    public static function getConfig(): array
    {
        return [
            'reservation-diary' => [
                'fields' => [
                    ['name' => 'date', 'label' => 'Tanggal', 'type' => 'date', 'required' => true],
                    ['name' => 'room_201_status', 'label' => 'Kamar 201 - Status', 'type' => 'select', 'options' => ['Arrival', 'Departure', 'Stayover', 'OCC', 'VA'], 'required' => true],
                    ['name' => 'room_201_guest', 'label' => 'Kamar 201 - Tamu', 'type' => 'text', 'required' => false],
                    ['name' => 'room_201_type', 'label' => 'Kamar 201 - Type', 'type' => 'text', 'required' => false],
                    ['name' => 'room_202_status', 'label' => 'Kamar 202 - Status', 'type' => 'select', 'options' => ['Arrival', 'Departure', 'Stayover', 'OCC', 'VA'], 'required' => true],
                    ['name' => 'room_202_guest', 'label' => 'Kamar 202 - Tamu', 'type' => 'text', 'required' => false],
                    ['name' => 'room_202_type', 'label' => 'Kamar 202 - Type', 'type' => 'text', 'required' => false],
                    ['name' => 'room_203_status', 'label' => 'Kamar 203 - Status', 'type' => 'select', 'options' => ['Arrival', 'Departure', 'Stayover', 'OCC', 'VA'], 'required' => true],
                    ['name' => 'room_203_guest', 'label' => 'Kamar 203 - Tamu', 'type' => 'text', 'required' => false],
                    ['name' => 'room_203_type', 'label' => 'Kamar 203 - Type', 'type' => 'text', 'required' => false],
                    ['name' => 'room_205_status', 'label' => 'Kamar 205 - Status', 'type' => 'select', 'options' => ['Arrival', 'Departure', 'Stayover', 'OCC', 'VA'], 'required' => true],
                    ['name' => 'room_205_guest', 'label' => 'Kamar 205 - Tamu', 'type' => 'text', 'required' => false],
                    ['name' => 'room_205_type', 'label' => 'Kamar 205 - Type', 'type' => 'text', 'required' => false],
                    ['name' => 'room_301_status', 'label' => 'Kamar 301 - Status', 'type' => 'select', 'options' => ['Arrival', 'Departure', 'Stayover', 'OCC', 'VA'], 'required' => true],
                    ['name' => 'room_301_guest', 'label' => 'Kamar 301 - Tamu', 'type' => 'text', 'required' => false],
                    ['name' => 'room_301_type', 'label' => 'Kamar 301 - Type', 'type' => 'text', 'required' => false],
                ],
                'answers' => [
                    'date' => '2026-07-03',
                    'room_201_status' => 'Departure',
                    'room_201_guest' => 'Ratna Kusuma',
                    'room_201_type' => 'Superior',
                    'room_202_status' => 'Arrival',
                    'room_202_guest' => 'New Guest',
                    'room_202_type' => 'Deluxe',
                    'room_203_status' => 'Departure',
                    'room_203_guest' => 'Hendra Wijaya',
                    'room_203_type' => 'Deluxe',
                    'room_205_status' => 'Stayover',
                    'room_205_guest' => 'Rina Hartati',
                    'room_205_type' => 'Superior',
                    'room_301_status' => 'Stayover',
                    'room_301_guest' => 'David Chen',
                    'room_301_type' => 'Deluxe',
                ],
                'clues' => [
                    'date' => 'Tanggal dalam diary.',
                    'room_201_status' => 'Status kamar 201 hari itu.',
                    'room_201_guest' => 'Nama tamu jika ada.',
                    'room_201_type' => 'Tipe kamar 201.',
                    'room_202_status' => 'Status kamar 202 hari itu.',
                    'room_202_guest' => 'Nama tamu jika ada.',
                    'room_202_type' => 'Tipe kamar 202.',
                    'room_203_status' => 'Status kamar 203 hari itu.',
                    'room_203_guest' => 'Nama tamu jika ada.',
                    'room_203_type' => 'Tipe kamar 203.',
                    'room_205_status' => 'Status kamar 205 hari itu.',
                    'room_205_guest' => 'Nama tamu jika ada.',
                    'room_205_type' => 'Tipe kamar 205.',
                    'room_301_status' => 'Status kamar 301 hari itu.',
                    'room_301_guest' => 'Nama tamu jika ada.',
                    'room_301_type' => 'Tipe kamar 301.',
                ],
            ],

            'conventional-chart' => [
                'fields' => [
                    ['name' => 'report_date', 'label' => 'Tanggal Laporan', 'type' => 'date', 'required' => true],
                    ['name' => 'room_201_type', 'label' => 'Kamar 201 - Tipe', 'type' => 'text', 'required' => true],
                    ['name' => 'room_201_status', 'label' => 'Kamar 201 - Status', 'type' => 'select', 'options' => ['OCC', 'VA', 'OOO', 'Arrival'], 'required' => true],
                    ['name' => 'room_201_guest', 'label' => 'Kamar 201 - Guest', 'type' => 'text', 'required' => false],
                    ['name' => 'room_202_type', 'label' => 'Kamar 202 - Tipe', 'type' => 'text', 'required' => true],
                    ['name' => 'room_202_status', 'label' => 'Kamar 202 - Status', 'type' => 'select', 'options' => ['OCC', 'VA', 'OOO', 'Arrival'], 'required' => true],
                    ['name' => 'room_203_type', 'label' => 'Kamar 203 - Tipe', 'type' => 'text', 'required' => true],
                    ['name' => 'room_203_status', 'label' => 'Kamar 203 - Status', 'type' => 'select', 'options' => ['OCC', 'VA', 'OOO', 'Arrival'], 'required' => true],
                    ['name' => 'room_301_type', 'label' => 'Kamar 301 - Tipe', 'type' => 'text', 'required' => true],
                    ['name' => 'room_301_status', 'label' => 'Kamar 301 - Status', 'type' => 'select', 'options' => ['OCC', 'VA', 'OOO', 'Arrival'], 'required' => true],
                    ['name' => 'room_301_guest', 'label' => 'Kamar 301 - Guest', 'type' => 'text', 'required' => false],
                    ['name' => 'room_302_type', 'label' => 'Kamar 302 - Tipe', 'type' => 'text', 'required' => true],
                    ['name' => 'room_302_status', 'label' => 'Kamar 302 - Status', 'type' => 'select', 'options' => ['OCC', 'VA', 'OOO', 'Arrival'], 'required' => true],
                    ['name' => 'total_occupied', 'label' => 'Total Occupied', 'type' => 'number', 'required' => true],
                    ['name' => 'total_vacant', 'label' => 'Total Vacant', 'type' => 'number', 'required' => true],
                    ['name' => 'occupancy_rate', 'label' => 'Occupancy Rate', 'type' => 'text', 'required' => true],
                ],
                'answers' => [
                    'report_date' => '2026-06-30',
                    'room_201_type' => 'Superior',
                    'room_201_status' => 'Arrival',
                    'room_201_guest' => 'New',
                    'room_202_type' => 'Deluxe',
                    'room_202_status' => 'OCC',
                    'room_203_type' => 'Deluxe',
                    'room_203_status' => 'Arrival',
                    'room_301_type' => 'Deluxe',
                    'room_301_status' => 'OCC',
                    'room_301_guest' => 'VIP',
                    'room_302_type' => 'Deluxe',
                    'room_302_status' => 'OCC',
                    'total_occupied' => '10',
                    'total_vacant' => '5',
                    'occupancy_rate' => '55.5%',
                ],
                'clues' => [
                    'report_date' => 'Tanggal laporan conventional chart.',
                    'room_201_type' => 'Tipe kamar 201.',
                    'room_201_status' => 'Status kamar 201 (OCC/VA/OOO/Arrival).',
                    'room_201_guest' => 'Jenis tamu jika OCC (VIP/New/Repeat).',
                    'room_202_type' => 'Tipe kamar 202.',
                    'room_202_status' => 'Status kamar 202.',
                    'room_203_type' => 'Tipe kamar 203.',
                    'room_203_status' => 'Status kamar 203.',
                    'room_301_type' => 'Tipe kamar 301.',
                    'room_301_status' => 'Status kamar 301.',
                    'room_301_guest' => 'Jenis tamu kamar 301.',
                    'room_302_type' => 'Tipe kamar 302.',
                    'room_302_status' => 'Status kamar 302.',
                    'total_occupied' => 'Jumlah kamar yang OCC.',
                    'total_vacant' => 'Jumlah kamar yang VA.',
                    'occupancy_rate' => 'Persentase occupancy = OCC / Total x 100%.',
                ],
            ],

            'reservation-confirmation' => [
                'fields' => [
                    ['name' => 'guest_name', 'label' => 'Nama Tamu', 'type' => 'text', 'required' => true],
                    ['name' => 'company', 'label' => 'Perusahaan', 'type' => 'text', 'required' => false],
                    ['name' => 'email', 'label' => 'Email', 'type' => 'email', 'required' => false],
                    ['name' => 'phone', 'label' => 'Telepon', 'type' => 'text', 'required' => true],
                    ['name' => 'booking_reference', 'label' => 'Booking Reference', 'type' => 'text', 'required' => true],
                    ['name' => 'check_in', 'label' => 'Check-in', 'type' => 'date', 'required' => true],
                    ['name' => 'check_out', 'label' => 'Check-out', 'type' => 'date', 'required' => true],
                    ['name' => 'duration', 'label' => 'Durasi (Malam)', 'type' => 'number', 'required' => true],
                    ['name' => 'room_type', 'label' => 'Tipe Kamar', 'type' => 'text', 'required' => true],
                    ['name' => 'room_rate', 'label' => 'Room Rate/Malam', 'type' => 'text', 'required' => true],
                    ['name' => 'room_charge_total', 'label' => 'Total Room Charge', 'type' => 'text', 'required' => true],
                    ['name' => 'tax', 'label' => 'Pajak (10%)', 'type' => 'text', 'required' => true],
                    ['name' => 'grand_total', 'label' => 'Grand Total', 'type' => 'text', 'required' => true],
                    ['name' => 'payment_method', 'label' => 'Pembayaran', 'type' => 'text', 'required' => true],
                    ['name' => 'eta', 'label' => 'ETA', 'type' => 'text', 'required' => true],
                    ['name' => 'eta_date', 'label' => 'ETA Date', 'type' => 'date', 'required' => true],
                    ['name' => 'flight', 'label' => 'Flight', 'type' => 'text', 'required' => false],
                ],
                'answers' => [
                    'guest_name' => 'David Chen',
                    'company' => 'David Chen Consulting',
                    'email' => 'david.chen@consulting.sg',
                    'phone' => '+65 9876 5432',
                    'booking_reference' => 'INV-20260628-0004',
                    'check_in' => '2026-06-30',
                    'check_out' => '2026-07-05',
                    'duration' => '5',
                    'room_type' => 'Executive Room',
                    'room_rate' => '950000',
                    'room_charge_total' => '4750000',
                    'tax' => '475000',
                    'grand_total' => '5225000',
                    'payment_method' => 'Credit Card',
                    'eta' => '20.00',
                    'eta_date' => '2026-06-30',
                    'flight' => 'SQ 956',
                ],
                'clues' => [
                    'guest_name' => 'Nama tamu dalam konfirmasi.',
                    'company' => 'Nama perusahaan tamu jika ada.',
                    'email' => 'Email tamu untuk konfirmasi.',
                    'phone' => 'Nomor telepon tamu.',
                    'booking_reference' => 'Nomor referensi reservasi.',
                    'check_in' => 'Tanggal check-in.',
                    'check_out' => 'Tanggal check-out.',
                    'duration' => 'Jumlah malam menginap.',
                    'room_type' => 'Tipe kamar yang dipesan.',
                    'room_rate' => 'Harga kamar per malam.',
                    'room_charge_total' => 'Total room charge = rate x malam.',
                    'tax' => 'Pajak 10% dari room charge.',
                    'grand_total' => 'Grand total termasuk pajak.',
                    'payment_method' => 'Metode pembayaran yang digunakan.',
                    'eta' => 'Estimated time of arrival.',
                    'eta_date' => 'Tanggal ETA.',
                    'flight' => 'Nomor penerbangan jika ada.',
                ],
            ],
        ];
    }
}
