<?php

namespace App\Services\ELearning;

class ReservationFormConfig
{
    public static function getConfig(): array
    {
        return [
            'reservation-form' => [
                'fields' => [
                    ['name' => 'guest_name', 'label' => 'Nama Tamu', 'type' => 'text', 'required' => true],
                    ['name' => 'company', 'label' => 'Perusahaan', 'type' => 'text', 'required' => false],
                    ['name' => 'address', 'label' => 'Alamat', 'type' => 'textarea', 'required' => true],
                    ['name' => 'phone_office', 'label' => 'Telepon Kantor', 'type' => 'text', 'required' => false],
                    ['name' => 'phone_mobile', 'label' => 'HP', 'type' => 'text', 'required' => true],
                    ['name' => 'email', 'label' => 'Email', 'type' => 'email', 'required' => false],
                    ['name' => 'arrival_date', 'label' => 'Tanggal Arrival', 'type' => 'date', 'required' => true],
                    ['name' => 'departure_date', 'label' => 'Tanggal Departure', 'type' => 'date', 'required' => true],
                    ['name' => 'duration', 'label' => 'Durasi (Malam)', 'type' => 'number', 'required' => true],
                    ['name' => 'room_type', 'label' => 'Tipe Kamar', 'type' => 'select', 'options' => ['Standard', 'Superior', 'Deluxe', 'Executive', 'Suite'], 'required' => true],
                    ['name' => 'number_of_rooms', 'label' => 'Jumlah Kamar', 'type' => 'number', 'required' => true],
                    ['name' => 'number_of_guests', 'label' => 'Jumlah Tamu', 'type' => 'number', 'required' => true],
                    ['name' => 'room_rate', 'label' => 'Room Rate/Malam', 'type' => 'text', 'required' => true],
                    ['name' => 'total_estimate', 'label' => 'Total Estimate', 'type' => 'text', 'required' => true],
                    ['name' => 'floor_preference', 'label' => 'Lantai Preferred', 'type' => 'text', 'required' => false],
                    ['name' => 'special_request_1', 'label' => 'Request 1', 'type' => 'text', 'required' => false],
                    ['name' => 'special_request_2', 'label' => 'Request 2', 'type' => 'text', 'required' => false],
                    ['name' => 'payment_method', 'label' => 'Pembayaran', 'type' => 'text', 'required' => true],
                ],
                'answers' => [
                    'guest_name' => 'Hendra Wijaya',
                    'company' => 'PT Wijaya Corpora',
                    'address' => 'Jl. Gatot Subroto No. 88, Surabaya',
                    'phone_office' => '031-7654321',
                    'phone_mobile' => '081234567890',
                    'email' => 'hendra.wijaya@wijayacorpora.co.id',
                    'arrival_date' => '2026-06-29',
                    'departure_date' => '2026-07-02',
                    'duration' => '3',
                    'room_type' => 'Deluxe',
                    'number_of_rooms' => '1',
                    'number_of_guests' => '2',
                    'room_rate' => '850000',
                    'total_estimate' => '2805000',
                    'floor_preference' => '4th floor or above',
                    'special_request_1' => 'Non-smoking room',
                    'special_request_2' => 'King size bed',
                    'payment_method' => 'Company Account',
                ],
                'clues' => [
                    'guest_name' => 'Nama pemesan reservasi.',
                    'company' => 'Nama perusahaan pemesan.',
                    'address' => 'Alamat lengkap.',
                    'phone_office' => 'Nomor telepon kantor.',
                    'phone_mobile' => 'Nomor HP pemesan.',
                    'email' => 'Email untuk konfirmasi.',
                    'arrival_date' => 'Tanggal check-in.',
                    'departure_date' => 'Tanggal check-out.',
                    'duration' => 'Jumlah malam menginap.',
                    'room_type' => 'Tipe kamar yang dipesan.',
                    'number_of_rooms' => 'Jumlah kamar yang dipesan.',
                    'number_of_guests' => 'Jumlah tamu dewasa.',
                    'room_rate' => 'Harga kamar per malam.',
                    'total_estimate' => 'Estimasi total + pajak 10%.',
                    'floor_preference' => 'Preferensi lantai kamar.',
                    'special_request_1' => 'Request khusus untuk kamar.',
                    'special_request_2' => 'Request tambahan.',
                    'payment_method' => 'Metode pembayaran reservasi.',
                ],
            ],

            'reservation-slip' => [
                'fields' => [
                    ['name' => 'guest_name', 'label' => 'Nama Tamu', 'type' => 'text', 'required' => true],
                    ['name' => 'company', 'label' => 'Perusahaan', 'type' => 'text', 'required' => false],
                    ['name' => 'booking_reference', 'label' => 'Booking Reference', 'type' => 'text', 'required' => true],
                    ['name' => 'arrival_date', 'label' => 'Arrival Date', 'type' => 'date', 'required' => true],
                    ['name' => 'departure_date', 'label' => 'Departure Date', 'type' => 'date', 'required' => true],
                    ['name' => 'room_type', 'label' => 'Room Type', 'type' => 'text', 'required' => true],
                    ['name' => 'room_number', 'label' => 'Room Number', 'type' => 'text', 'required' => true],
                    ['name' => 'room_rate', 'label' => 'Room Rate/Malam', 'type' => 'text', 'required' => true],
                    ['name' => 'number_of_guests', 'label' => 'Jumlah Tamu', 'type' => 'number', 'required' => true],
                    ['name' => 'total_room_charge', 'label' => 'Total Room Charge', 'type' => 'text', 'required' => true],
                    ['name' => 'tax', 'label' => 'Tax (10%)', 'type' => 'text', 'required' => true],
                    ['name' => 'grand_total', 'label' => 'Grand Total', 'type' => 'text', 'required' => true],
                    ['name' => 'payment_method', 'label' => 'Payment Method', 'type' => 'text', 'required' => true],
                    ['name' => 'account_name', 'label' => 'Account Name', 'type' => 'text', 'required' => false],
                    ['name' => 'eta', 'label' => 'ETA', 'type' => 'text', 'required' => true],
                    ['name' => 'flight', 'label' => 'Flight', 'type' => 'text', 'required' => false],
                ],
                'answers' => [
                    'guest_name' => 'Linda Tanoto',
                    'company' => 'PT Maju Bersama',
                    'booking_reference' => 'INV-20260628-0003',
                    'arrival_date' => '2026-06-29',
                    'departure_date' => '2026-06-30',
                    'room_type' => 'Superior Room',
                    'room_number' => '207',
                    'room_rate' => '650000',
                    'number_of_guests' => '1',
                    'total_room_charge' => '650000',
                    'tax' => '65000',
                    'grand_total' => '715000',
                    'payment_method' => 'Company Account',
                    'account_name' => 'PT Maju Bersama',
                    'eta' => '16.45',
                    'flight' => 'JT 890',
                ],
                'clues' => [
                    'guest_name' => 'Nama tamu yang melakukan reservasi.',
                    'company' => 'Nama perusahaan jika ada.',
                    'booking_reference' => 'Nomor referensi reservasi.',
                    'arrival_date' => 'Tanggal check-in.',
                    'departure_date' => 'Tanggal check-out.',
                    'room_type' => 'Tipe kamar yang dipesan.',
                    'room_number' => 'Nomor kamar yang dialokasikan.',
                    'room_rate' => 'Harga kamar per malam.',
                    'number_of_guests' => 'Jumlah tamu.',
                    'total_room_charge' => 'Total biaya kamar = rate x malam.',
                    'tax' => 'Pajak 10% dari room charge.',
                    'grand_total' => 'Total + pajak.',
                    'payment_method' => 'Metode pembayaran yang digunakan.',
                    'account_name' => 'Nama akun untuk company billing.',
                    'eta' => 'Estimated time of arrival.',
                    'flight' => 'Nomor penerbangan jika ada.',
                ],
            ],

            'expected-arrival' => [
                'fields' => [
                    ['name' => 'arrival_date', 'label' => 'Tanggal Arrival', 'type' => 'date', 'required' => true],
                    ['name' => 'room_201_guest', 'label' => 'Kamar 201 - Tamu', 'type' => 'text', 'required' => true],
                    ['name' => 'room_201_origin', 'label' => 'Kamar 201 - Origin', 'type' => 'text', 'required' => true],
                    ['name' => 'room_201_eta', 'label' => 'Kamar 201 - ETA', 'type' => 'text', 'required' => true],
                    ['name' => 'room_201_flight', 'label' => 'Kamar 201 - Flight', 'type' => 'text', 'required' => true],
                    ['name' => 'room_201_transport', 'label' => 'Kamar 201 - Transport', 'type' => 'text', 'required' => true],
                    ['name' => 'room_201_purpose', 'label' => 'Kamar 201 - Purpose', 'type' => 'text', 'required' => true],
                    ['name' => 'room_201_los', 'label' => 'Kamar 201 - LOS', 'type' => 'number', 'required' => true],
                    ['name' => 'room_201_rate', 'label' => 'Kamar 201 - Rate', 'type' => 'text', 'required' => true],
                    ['name' => 'room_203_guest', 'label' => 'Kamar 203 - Tamu', 'type' => 'text', 'required' => true],
                    ['name' => 'room_203_origin', 'label' => 'Kamar 203 - Origin', 'type' => 'text', 'required' => true],
                    ['name' => 'room_203_eta', 'label' => 'Kamar 203 - ETA', 'type' => 'text', 'required' => true],
                    ['name' => 'room_203_flight', 'label' => 'Kamar 203 - Flight', 'type' => 'text', 'required' => true],
                    ['name' => 'room_203_transport', 'label' => 'Kamar 203 - Transport', 'type' => 'text', 'required' => true],
                    ['name' => 'room_203_purpose', 'label' => 'Kamar 203 - Purpose', 'type' => 'text', 'required' => true],
                    ['name' => 'room_203_los', 'label' => 'Kamar 203 - LOS', 'type' => 'number', 'required' => true],
                    ['name' => 'room_203_rate', 'label' => 'Kamar 203 - Rate', 'type' => 'text', 'required' => true],
                    ['name' => 'total_arrival', 'label' => 'Total Arrival', 'type' => 'number', 'required' => true],
                    ['name' => 'expected_revenue', 'label' => 'Expected Revenue', 'type' => 'text', 'required' => true],
                ],
                'answers' => [
                    'arrival_date' => '2026-06-30',
                    'room_201_guest' => 'Ratna Kusuma',
                    'room_201_origin' => 'Jakarta',
                    'room_201_eta' => '10.30',
                    'room_201_flight' => 'GA 601',
                    'room_201_transport' => 'Hotel Transfer',
                    'room_201_purpose' => 'Business',
                    'room_201_los' => '2',
                    'room_201_rate' => '750000',
                    'room_203_guest' => 'Hendra Wijaya',
                    'room_203_origin' => 'Surabaya',
                    'room_203_eta' => '14.00',
                    'room_203_flight' => 'SI 205',
                    'room_203_transport' => 'Airport Pickup',
                    'room_203_purpose' => 'Conference',
                    'room_203_los' => '3',
                    'room_203_rate' => '850000',
                    'total_arrival' => '4',
                    'expected_revenue' => '7950000',
                ],
                'clues' => [
                    'arrival_date' => 'Tanggal arrival yang diprediksi.',
                    'room_201_guest' => 'Nama tamu kamar 201.',
                    'room_201_origin' => 'Kota asal tamu 201.',
                    'room_201_eta' => 'Waktu kedatangan tamu 201.',
                    'room_201_flight' => 'Nomor penerbangan tamu 201.',
                    'room_201_transport' => 'Jenis transportasi yang dibutuhkan.',
                    'room_201_purpose' => 'Tujuan kunjungan tamu 201.',
                    'room_201_los' => 'Lama menginap tamu 201.',
                    'room_201_rate' => 'Rate kamar 201.',
                    'room_203_guest' => 'Nama tamu kamar 203.',
                    'room_203_origin' => 'Kota asal tamu 203.',
                    'room_203_eta' => 'Waktu kedatangan tamu 203.',
                    'room_203_flight' => 'Nomor penerbangan tamu 203.',
                    'room_203_transport' => 'Jenis transportasi yang dibutuhkan.',
                    'room_203_purpose' => 'Tujuan kunjungan tamu 203.',
                    'room_203_los' => 'Lama menginap tamu 203.',
                    'room_203_rate' => 'Rate kamar 203.',
                    'total_arrival' => 'Total tamu yang expected arrival.',
                    'expected_revenue' => 'Total expected revenue dari semua kamar.',
                ],
            ],
        ];
    }
}
